action:
  - changed-files:
    - any-glob-to-any-file: '.github/*'
supperthomas:
  - changed-files:
    - any-glob-to-any-file: 'source/00_supperthomas'
xupenghu:
  - changed-files:
    - any-glob-to-any-file: 'source/03_xupenghu'
