name: Labeler

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Label PR
        uses: actions/labeler@master
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
